const files = [
  // require("./_circle-pitch-scale.json"),
  // require("./_circle-sort-key.json"),
  // require("./_fill-antialias.json"),
  // require("./_fill-sort-key.json"),
  // require("./_icon-anchor.json"),
  // require("./_icon-color.json"),
  // require("./_icon-halo-blur.json"),
  // require("./_icon-halo-color.json"),
  // require("./_icon-halo-width.json"),
  // require("./_icon-ignore-placement.json"),
  // require("./_icon-offset.json"),
  // require("./_icon-optional.json"),
  // require("./_icon-padding.json"),
  // require("./_icon-pitch-alignment.json"),
  // require("./_icon-rotation-alignment.json"),
  // require("./_icon-text-fit-padding.json"),
  // require("./_icon-text-fit.json"),
  // require("./_line-gradient.json"),
  // require("./_line-miter-limit.json"),
  // require("./_line-offset.json"),
  // require("./_line-round-limit.json"),
  // require("./_line-sort-key.json"),
  // require("./_raster-fade-duration.json"),
  // require("./_symbol-avoid-edges.json"),
  // require("./_symbol-placement.json"),
  // require("./_symbol-sort-key.json"),
  // require("./_symbol-spacing.json"),
  // require("./_symbol-z-order.json"),
  // require("./_text-ignore-placement.json"),
  // require("./_text-max-angle.json"),
  // require("./_text-max-width.json"),
  // require("./_text-offset.json"),
  // require("./_text-optional.json"),
  // require("./_text-padding.json"),
  // require("./_text-pitch-alignment.json"),
  // require("./_text-radial-offset.json"),
  // require("./_text-rotation-alignment.json"),
  // require("./_text-translate-anchor.json"),
  // require("./_text-variable-anchor.json"),
  // require("./_text-writing-mode.json"),
  require("./background-color.json"),
  require("./background-opacity.json"),
  require("./background-pattern.json"),
  require("./circle-blur.json"),
  require("./circle-color.json"),
  require("./circle-opacity.json"),
  require("./circle-pitch-alignment.json"),
  require("./circle-radius.json"),
  require("./circle-stroke-color.json"),
  require("./circle-stroke-opacity.json"),
  require("./circle-stroke-width.json"),
  require("./circle-translate-anchor.json"),
  require("./circle-translate.json"),
  require("./fill-color.json"),
  require("./fill-opacity.json"),
  require("./fill-outline-color.json"),
  require("./fill-pattern.json"),
  require("./fill-translate-anchor.json"),
  require("./fill-translate.json"),
  require("./icon-allow-overlap.json"),
  require("./icon-image.json"),
  require("./icon-keep-upright.json"),
  require("./icon-opacity.json"),
  require("./icon-rotate.json"),
  require("./icon-size.json"),
  require("./icon-translate.json"),
  require("./line-blur.json"),
  require("./line-cap.json"),
  require("./line-color.json"),
  require("./line-dasharray.json"),
  require("./line-gap-width.json"),
  require("./line-join.json"),
  require("./line-opacity.json"),
  require("./line-pattern.json"),
  require("./line-translate-anchor.json"),
  require("./line-translate.json"),
  require("./line-width.json"),
  require("./raster-brightness-max.json"),
  require("./raster-brightness-min.json"),
  require("./raster-contrast.json"),
  require("./raster-hue-rotate.json"),
  require("./raster-opacity.json"),
  require("./raster-resampling.json"),
  require("./raster-saturation.json"),
  require("./text-allow-overlap.json"),
  require("./text-anchor.json"),
  require("./text-color.json"),
  require("./text-field.json"),
  require("./text-font.json"),
  require("./text-halo-blur.json"),
  require("./text-halo-color.json"),
  require("./text-halo-width.json"),
  require("./text-justify.json"),
  require("./text-keep-upright.json"),
  require("./text-letter-spacing.json"),
  require("./text-line-height.json"),
  require("./text-opacity.json"),
  require("./text-rotate.json"),
  require("./text-size.json"),
  require("./text-transform.json"),
  require("./text-translate.json"),
]

module.exports = files.map(file => {
  return file;
});
